name: Deploy minimal Flask app to Azure Web App

on:
  push:
    branches:
      - temp
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip deployment package
        run: |
          mkdir package
          cp app.py requirements.txt package/
          cd package
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9014872D01D4418690A52D2E3FA9909C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_23ADA7D73BC1421DBB3E869AD0BE8A78 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_01E70137F79446BF8E34F0AE0D25970C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bead-divvy'
          slot-name: 'Production'
          package: release.zip
